### ISSUE TITLE
SBCL Build Issues

### ISSUE THREAD

**Issue by theangelperalta** [fiddlerwoaroof/objc-lisp-bridge#2]
I've read the README, and I saw you and other contributors had issues building with SBCL. I have diagnosed the issues and found two problems. First, the compiled and bundled SBCL binary cannot find the `libnsrect-expose.dylib` in either the bundle or other expected directories. Second, swank fails to start on launch once I patch the first issue (I place a soft link to `libnsrect-expose.dylib` in `/usr/local/lib/`). Temporary solution is to comment out the swank code altogether until we further the diagnose the issue with swank and SBCL.

**Comment by defmacro-jam** [comment]
It can also be solved by setting the current directory to the directory containing `libnsrect-expose.dylib` with something like 
```
(sb-posix:chdir "~/quicklisp/local-projects/objc-lisp-bridge/")
```
There's a more general problem with hardcoding the quicklisp paths anyway.  My quicklisp for SBCL is in `~/.quicklisp-sbcl/` because I have a quicklisp directory for each of the CL implementations I use.

**Comment by fiddlerwoaroof** [comment]
I just pushed a code change that uses cffi-libffi to eliminate that dylib, let me know if it works?  For me, if I do:

```sh
% cd objc-lisp-bridge
% make CL=$(which sbcl)
% demo.app/Contents/MacOS/demo-app
```

I get this screen:

<img width="242" alt="image" src="https://user-images.githubusercontent.com/808745/111060485-0b7f2a00-8452-11eb-99ce-4e2476d57456.png">

**Comment by defmacro-jam** [comment]
Yes sir!  Works great!
